version: '3.3'

services:
  nginx:
    image: bindex_nginx
    env_file: .env
    environment:
      HOSTNAME: 'nginx'
    depends_on:
      - pm2
    ports:
      - 80:8080
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,cached
    networks:
      - webnet

  pm2:
    image: bindex_pm2
    environment:
      HOSTNAME: 'pm2'
      NODE_ENV: 'production'
      HOST: 0.0.0.0
      PORT: 5000
      MONGO_HOST: 'mongodb'
    depends_on:
      - mongodb
    networks:
      - webnet

  mongodb:
    image: mongo
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
    attachable: true
