version: '2'

services:
  nginx:
    image: bindex_nginx
    env_file: .env
    environment:
      HOSTNAME: 'nginx'
    depends_on:
      - pm2
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,cached
    networks:
      - default

  pm2:
    image: bindex_pm2
    environment:
      HOSTNAME: 'pm2'
      NODE_ENV: 'production'
      PORT: 5000
      POSTGRES_HOST: 'postgres'
    depends_on:
      - mongodb
    networks:
      - default

  postgres:
    image: postgres
    networks:
      - default

networks:
  default:
    driver: bridge
